apiVersion: apps/v1
kind: Deployment
metadata:
  name: festivos-api
  namespace: festivos-api
  labels:
    app: festivos-api
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: festivos-api
      version: v1
  template:
    metadata:
      labels:
        app: festivos-api
        version: v1
    spec:
      containers:
      - name: festivos-api
        image: 476114125818.dkr.ecr.us-east-1.amazonaws.com/arquitectura-avanzada-app:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        # Spring Boot configuration
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SERVER_PORT
          value: "8080"
        
        # Database configuration from External Secrets (RDS)
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: rds-secret
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: rds-secret
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rds-secret
              key: SPRING_DATASOURCE_PASSWORD
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          valueFrom:
            secretKeyRef:
              name: rds-secret
              key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        
        # JWT Secret from External Secrets
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
        
        # JPA/Hibernate configuration
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "validate"
        - name: SPRING_JPA_SHOW_SQL
          value: "false"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.PostgreSQLDialect"
        
        # Actuator configuration
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "health,info,metrics"
        - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
          value: "always"
        
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        # Usar TCP probe para liveness - más simple y confiable
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        # Usar TCP probe para readiness - evita problemas con Spring Security
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
